# Base config to merge into
# If an absolute path is given then it is used
# Otherwise it is assumed to me reative to the directory of this file
base: "MOOJ1142_M2_base.yaml"

# Cluster name
# Used both for the output path as well as to load presets
name: "MOOJ1142_M2"

# Define the model
model:
  # Unit conversion to apply at the end
  # Will be evaled
  unit_conversion: "float(wu.get_da(constants['z'])*wu.y2K_RJ(constants['freq'], constants['Te'])*wu.XMpc/wu.me)"
  # Structure to include in the model
  structures:
    # Name of the first structure
    a10:
      structure: "a10" # What type of structure it is
      # Parameters for the structure
      parameters:
        dx_1: # Name of the first parameter
          value: 0.0 # Value to use/start at, will be evaled
          # Set to True for the rounds where we want to fit this param
          # If you set it to just True of False it will be that for all rounds
          # If not provided assumed to be False
          to_fit: True 
          # Range to prior to, will be evaled
          priors: [-9.0, 9.0]
        dy_1:
          value: 0.0
          to_fit: True 
          priors: [-9.0, 9.0]
        dz_1:
          value: 0.0 
          priors: [-9.0, 9.0]
        theta:
          value: 0.0
          priors: [0, 6.29]
        P0:
          value: 8.403
          priors: [6, 10]
        c500:
          value: 1.177 
          priors: [1, 3]
        m500:
          value: "1.5e15"
          to_fit: True 
          priors: ["1e14", "1e16"]
        gamma:
          value: .3081 
          priors: [.05, 1]
          to_fit: True 
        alpha:
          value: 1.551 
          priors: [.05, 3]
          to_fit: True 
        beta:
          value: 5.4905 
          priors: [.05, 10]
          to_fit: True 
        z:
          value: 0.97 
          priors: [.9, 1]
    ps_gauss:
      structure: "gaussian"
      parameters:
        dx_g:
          value: 19.0
          to_fit: True
          priors: [10.0, 28.0]
        dy_g:
          value: -4.0
          to_fit: True
          priors: [-13.0, 5.0]
        sigma:
          value: 4.0
        amp_g:
          value: 0.01
          to_fit: True
